### ISSUE TITLE
Preparing to launching

### ISSUE THREAD

**Issue by guilhermecomum** [emacs-love/weblorg#15]
- [x] Rename repo to weblorg
- [x] Rename functions and references to blorg
- [x] Add link to github on weblorg page
- [ ] Blog post about weblorg
- [x] Fix PR on melpa
- [ ] Fix API docs
- [ ] Add minimum documentation
  - installation
  - one page website tutorial
  - blog tutorial

**Comment by clarete** [comment]
still missing the blog tutorial, but we've launched the first version already 😄
