### ISSUE TITLE
string=: Wrong type argument: stringp, 47

### ISSUE THREAD

**Issue by bbigras** [emacs-love/weblorg#19]
I got `string=: Wrong type argument: stringp, 47` when trying to eval `examples/simpleblog/publish.el`.

Any ideas?

**Comment by bbigras** [comment]
It seems fine if I install weblorg from melpa.

**Comment by clarete** [comment]
Oh nice. I bet the `templatel` dependency was outdated. Please re-open this ticket or open a new one if you have any issues!
