### ISSUE TITLE
docs: syntax highlight when exporting src blocks

### ISSUE THREAD

**Issue by lccambiaghi** [emacs-love/weblorg#24]
This is not an issue but rather a suggestion! I noticed that in order for the org src blocks to be exported correctly we need to install the correct elisp dependencies.

What happened to me was that when exporting locally the src blocks would correctly be syntax highlighted but on the server (I am using GitHub pages) they would not. I have just added `clojure-mode` to the server and the highlighting worked.

Thanks again for your brilliant package!

**Comment by clarete** [comment]
Thank you for bringing this up @lccambiaghi! Really appreciate the attention to the docs as this is one of the things I really want to iron out.  I took a stab at documenting it here: https://emacs.love/weblorg/doc/theming.html#syntax-highlight-of-source-code-blocks

Please let me know what you think and feel free to re-open this ticket if you feel like any changes are needed or open a new one if you deem necessary! 🙇🏾
