### ISSUE TITLE
Bug: the default logo is unreachable

### ISSUE THREAD

**Issue by lccambiaghi** [emacs-love/weblorg#34]
In the example `style.css` there is a reference to a `blorg.png` that is unreachable: https://github.com/emacs-love/weblorg/blob/main/themes/default/static/style.css#L70 .

**Comment by lccambiaghi** [comment]
A quick Google brought me to this issue: https://github.com/itsthatguy/avatars-api-middleware/issues/108

So I think it is just enough to replace the URL with this new one: https://api.hello-avatar.com/adorables/100/blorg.png

**Comment by clarete** [comment]
Thanks for filing this ticket and sorry for all the time it took to get to it! 😅 
but it's finally there, the default template has been touched up and this is how it looks like now:

![image](https://user-images.githubusercontent.com/1459190/132101733-291398fa-5e29-45a7-aedc-89b1528386d4.png)
