### ISSUE TITLE
weblorg-export warnings

### ISSUE THREAD

**Issue by markokocic** [emacs-love/weblorg#41]
When I try to run `weblorg-export` interactively from the Emacs I got a bunch of prompts like:

```Buffer post-1.org modified; kill anyway? (yes or no)```

In order to publish I have to type `yes` for each file. This makes the publishing process annoying. Fixing this issue would make the interactive writing process much faster, since it would be enough to just call `weblorg-exprort` from inside emacs instead switching to another console window, running the `emacs --script publish.el`, waiting for emacs to start initialize and load all needed package, write output filer, and then switch back to emacs.

**Comment by clarete** [comment]
Hi @markokocic thanks for taking the time to open this issue 🙇🏾 this is interesting; I think I'm just not properly closing the temporary buffers created for parsing each Org-mode files.  Sorry about the annoyance! Will get a fix for this! 🔜  😄

**Comment by clarete** [comment]
now with #47 merged, it'd be really cool to fix this 😄
