### ISSUE TITLE
Transform filetags on a post into a collection for templates

### ISSUE THREAD

**Issue by AblatedSprocket** [emacs-love/weblorg#45]
Right now when I use the filetags property in a template, it's a string like `:emacs:general:` Would it be possible to split the tags into a collection you can iterate over?

**Comment by clarete** [comment]
Hi @AblatedSprocket thanks for taking the time to post this issue! And this sounds like a great idea, yeah!

Just documenting in case you or anybody else wants to take a stab at it, we need to split the `filetags` property with [split-string](https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Strings.html#index-split_002dstring).

And I'd fit that in within this function [weblorg--parse-org-keyword](https://github.com/emacs-love/weblorg/blob/main/weblorg.el#L1043).

I'd also add a test for that 😄

**Comment by AblatedSprocket** [comment]
I've wanted to get involved in the project, I'll try to find some bandwidth to work on this. Thank you for explaining what needs to be done.

**Comment by AblatedSprocket** [comment]
Making the change as you suggested does create a collection of tags accessible to the templates. It also has the unhappy side-effect of forcing the filenames of the generated HTML files to be the full path of the Org file, but hyphenated. So path/to/my/post.org generates a file named path-to-my-post-org.html. I'm trying to understand why this happens, but my elisp is not great. In case anyone is curious, the modified function is below:
```
(defun weblorg--parse-org-keyword (keyword)
  "Parse a single Org-Mode document KEYWORD.

If it's a date field, it will return a timestamp tuple instead of
the value string.  The user will have to use the `strftime`
template filter to display a nicely formatted string.

If it's a filetag field, it will return a collection of strings.
The user will have to iterate over the collection to get all keywords."
  (let ((key (downcase (org-element-property :key keyword)))
        (value (org-element-property :value keyword)))
    (cons
     key
     (cond ((string= key "date")
            ;; use the deprecated signature of `encode-time' to keep
            ;; compatibility to Emacs 26x.
            (apply #'encode-time (org-parse-time-string value)))
           ((string= key "filetags")
            (split-string value ":" t))))))
```

**Comment by clarete** [comment]
Hi @AblatedSprocket, thank you so much for writing this up.  This looks pretty good as far as I can tell.  I would probably think of adding a test to the `t/test-weblorg.el` file for parsing the date of an actual Org-Mode file, but I think the code change is mostly there 😄 

On the file name that is being generated from weblorg, I can't see anything in your change that could be causing that. We have an issue tracking something slightly different (#27).  If you don't figure that out, I'd still suggest to get the PR up, so then I can test your code in my environment!

Pretty exciting stuff!! Thank you for taking the time 🙇🏾

**Comment by clarete** [comment]
With the PR #50 merged, @AblatedSprocket do you think there's anything else we would need to do to cover this feature?

**Comment by AblatedSprocket** [comment]
Sorry, I don't know how I missed your comment. This feature's got everything I need out of it. :)

**Comment by clarete** [comment]
No worries! Thanks for confirming!! 😄
