### ISSUE TITLE
Docs regarding site global parameters are incomplete

### ISSUE THREAD

**Issue by thecashewtrader** [emacs-love/weblorg#60]
While trying to setup my (soon to be) blog, I noticed that the site global parameters are not documented. On looking around, I found this acknowledged [here](https://github.com/emacs-love/weblorg/issues/37#issuecomment-789363779), so thought of making a separate issue.

I am currently figuring out how exactly weblorg works, and hopefully should be able to contribute docs by next week.

**Comment by clarete** [comment]
thank you for taking the time to report this issue! And for opening a PR against our documentation with the fixes!
