### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by markokocic** [emacs-love/weblorg#79]
Hi @clarete , 

There has not been any commit since almost a year. In the meantime, weblorg is [not usable any more](#78 ) with the latest org-mode version in its current state.

There has been a [pull request](#75 ) to remedy that for some time, but it's not merged for a long time. 

If the project is to continue to be usable, we need at least this pull request and a new release to melpa.

Can you please clarify your plans regarding this project and future direction?

**Comment by markokocic** [comment]
To clarify, there are already some pending pull requests, that bring weblorg to be usable again, and some small fixes. For example, #75 #76 and #77 by @nanzhong and #70 by @mgmarlow would make for a nice first release.
#57 would also be interesting to have, not sure about its state though.

**Comment by markokocic** [comment]
Since there is no answer to this question, I pulled the fixes from @nanzhong into my [fork](markokocic/weblorg) and proposed a creation of a new package weblorg-ng in melpa. Let's see if it will be accepted.

I'll delete my fork as soon as this project is revived again.

**Comment by clarete** [comment]
Hey @markokocic 👋 

I really truly appreciate you opening this issue. It creates the space to talk about the obvious hiatus in the project. Life has taken a bit of a turn and I was a bit too aggressive with my GitHub notifications and spent little to no time in projects that didn't directly relate to my daily work.

That being said, I am extremely grateful that you and other contributors have seen value in the code that's currently written in this project.  And it'd be a shame if you couldn't continue to take advantage of that even while willing to contribute your own time to help keeping the project updated with the latest Emacs changes.

Do you think it'd be a good solution to try and give you and @nanzhong contributor access so you guys have the time, you can apply these fixes on your own without me having to gatekeep things.

I'd also try and make the effort to review PRs and share thoughts as much as possible on design and implementation of anything you guys would want to take on.  I would unfortunately have very little to no time to writing code myself for the foreseeable future.

How does this sound as the immediate next step?  I'm all ears about what other solutions could look like! Let me know.

Also wanted to CC @guilhermecomum, as he's already in the contributor list and can possibly also chime in with new ideas 😄 

Cheers,
 -- Lincoln

**Comment by nanzhong** [comment]
Happy to contribute my time to this if you're open to making me a contributor. Though I have to admit that my time will be somewhat limited since work and personal life right now are quite busy.

**Comment by markokocic** [comment]
Hi @clarete , glad you're back 🙂

Yes, if more people that use the project have write access, it would eventually keep going. I can't promise some big new features, but can contribute a fix or a feature here and there.

To avoid stagnation, you can also consider giving more people access to templatel and website repos too, since templatel is a key dependency and docs would need an update with every new feature.

Now, the next steps. Would you still consider reviewing and merging open pull request, or leave that to @nanzhong and other new contributors?

**Comment by markokocic** [comment]
Thanks @clarete 
IMHO templatel logically belongs to emacs-love org, since it's a major dependency.

**Comment by clarete** [comment]
OK, I moved `templatel` into the org as well, and added both of you with write access (is that the right permission level you guys need?)

**Comment by clarete** [comment]
Btw the websites are of course generated with weblorg, within their respective repositories! There is some updating needed in the `templatel` one but we’ll get to that 😄

**Comment by ccleberg** [comment]
@markokocic - Following up on this thread since the last release was over 3 years ago and the last commit was 8 months ago. Is there any maintenance being performed on weblorg since the updated on this thread last July?
